COX Shield: xPWM Exported APIs Refrence
xPWM Exported APIs Refrence
xPWM
CoX PWM Peripheral Interface APIs Refrence.
Functions
void xPWMInitConfigure (unsigned long ulBase, unsigned long ulChannel, unsigned long ulConfig)
Initialize and configure the PWM module.
unsigned long xPWMFrequencySet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulFrequency)
Set the PWM frequency of the PWM module.
unsigned long xPWMFrequencyConfig (unsigned long ulBase, unsigned long ulChannel, unsigned long ulConfig)
Set the PWM frequency of the PWM module.
unsigned long xPWMFrequencyGet (unsigned long ulBase, unsigned long ulChannel)
get the PWM frequency of the PWM module.
void xPWMOutputEnable (unsigned long ulBase, unsigned long ulChannel)
Enable the PWM output of the PWM module.
void xPWMOutputDisable (unsigned long ulBase, unsigned long ulChannel)
Disable the PWM output of the PWM module.
void xPWMStart (unsigned long ulBase, unsigned long ulChannel)
Start the PWM of the PWM module.
void xPWMStop (unsigned long ulBase, unsigned long ulChannel)
Stop the PWM of the PWM module.
void xPWMDutySet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulDuty)
Set the PWM duty of the PWM module.
unsigned long xPWMDutyGet (unsigned long ulBase, unsigned long ulChannel)
Get the PWM duty of the PWM module.
void xPWMIntEnable (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntType)
Enable the PWM interrupt of the PWM module.
void xPWMIntDisable (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntType)
Disable the PWM interrupt of the PWM module.
void xPWMIntFlagGet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntType)
Get the PWM interrupt flag of the PWM module.
void xPWMIntCallbackInit (unsigned long ulBase, xtEventCallback xtPWMCallback)
Init interrupts callback for the PWM timer.
Detailed Description
CoX PWM Peripheral Interface APIs Refrence.
xPWM API Reference.
@verbatim
//! +---------------------—+-------------—+-----—+ //! |xPWM API | CoX | NUC1xx | //! |---------------------—|-------------—|-----—| //! |xPWMInitConfigure | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMFrequencySet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMFrequencyConfig | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMFrequencyGet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMOutputEnable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMOutputDisable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMStart | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMStop | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMDutySet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMDutyGet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMIntEnable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMIntDisable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMIntFlagGet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xPWMIntCallbackInit | Mandatory | Y | //! |---------------------—|-------------—|-----—| //!
Function Documentation
void xPWMInitConfigure (unsigned long ulBase, unsigned long ulChannel, unsigned long ulConfig)
Initialize and configure the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulConfig is the configuration of PWM channel. Details please refer to xPWM Config Type.
This function is to initialize and configure channel of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulConfig parameter is the logical OR of four values: The PWM mode, Inverter or not,and use dead zero or not and dead zone length. xPWM_ONE_SHOT_MODE,xPWM_TOGGLE_MODE is the mode selecet. xPWM_OUTPUT_INVERTER_EN, xPWM_OUTPUT_INVERTER_DIS is to enable Inverter or not. xPWM_DEAD_ZONE_EN xPWM_DEAD_ZONE_DIS is to enable dead zone Generator or not. The dead zone length will be set at the 16~23 bits of the ulConfig. Details please refer to 2.CoX Mandatory and CoX Non-mandatory.
Note
When Dead-Zone Generator is enabled, the pair of PWM0 and PWM1 becomes a complementary pair for PWM group A and the pair of PWM4 and PWM5 becomes a complementary pair for PWM group B.
Returns
None.
Referenced by MSDCMotorPWMInit().
unsigned long xPWMFrequencySet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulFrequency)
Set the PWM frequency of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulFrequency is the PWM frequency of PWM channel.
This function is to set the PWM frequency of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulFrequency parameter can be values: Any values ,ulFrequency > 0 && ulFrequency < PWM module input clock.
Note
Returns
the Actual Frequency of PWM.
Referenced by MSDCMotorSpeedSet().
unsigned long xPWMFrequencyConfig (unsigned long ulBase, unsigned long ulChannel, unsigned long ulConfig)
Set the PWM frequency of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulConfig is the configuration of PWM channel' frequency. Details please refer to xPWM Frequency Configure.
This function is to set the PWM frequency of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulConfig parameter is the logical OR of three values: The PreScale value, The Divider value and the PWM Counter Register value. Details please refer to xPWM_Freq_Config_CoX.
Note
Config will not the same since diff manu,but for NUC1xx is the above
Returns
the Actual Frequency of PWM.
Referenced by MSDCMotorPWMInit().
unsigned long xPWMFrequencyGet (unsigned long ulBase, unsigned long ulChannel)
get the PWM frequency of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
This function is to get the PWM frequency of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
Note
None
Returns
the Actual Frequency of PWM.
void xPWMOutputEnable (unsigned long ulBase, unsigned long ulChannel)
Enable the PWM output of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
This function is to enable the PWM output of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
Note
None
Returns
None.
Referenced by MSDCMotorPWMInit().
void xPWMOutputDisable (unsigned long ulBase, unsigned long ulChannel)
Disable the PWM output of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
This function is to disable the PWM output of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
Note
None
Returns
None.
void xPWMStart (unsigned long ulBase, unsigned long ulChannel)
Start the PWM of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
This function is to start the PWM of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
Note
None
Returns
None.
Referenced by MSDCMotorPWMInit(), and MSDCMotorSpeedSet().
void xPWMStop (unsigned long ulBase, unsigned long ulChannel)
Stop the PWM of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
This function is to stop the PWM of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
Note
None
Returns
None.
Referenced by MSDCMotorSpeedSet().
void xPWMDutySet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulDuty)
Set the PWM duty of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulDuty is the duty of PWM channel.
This function is to set the PWM duty of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulDuty parameter can be values: duty > 0 && duty <= 100.
Note
Duty should not be 0;
Returns
None.
Referenced by MSDCMotorPWMInit(), and MSDCMotorSpeedSet().
unsigned long xPWMDutyGet (unsigned long ulBase, unsigned long ulChannel)
Get the PWM duty of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
This function is to get the PWM duty of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
Note
None
Returns
the Actual duty of PWM.
void xPWMIntEnable (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntType)
Enable the PWM interrupt of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulIntType is the PWM channel interrupt type. Details please refer to xPWM Interrupt Type.
This function is to enable the PWM interrupt of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulIntType parameter can be values: xPWM_INT_PWM. Details please refer to 2.CoX Mandatory and CoX Non-mandatory.
Note
None
Returns
None.
void xPWMIntDisable (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntType)
Disable the PWM interrupt of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulIntType is the PWM channel interrupt type. Details please refer to xPWM Interrupt Type.
This function is to disable the PWM interrupt of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulIntType parameter can be values: xPWM_INT_PWM. Details please refer to 2.CoX Mandatory and CoX Non-mandatory.
Note
None
Returns
None.
void xPWMIntFlagGet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntType)
Get the PWM interrupt flag of the PWM module.
Parameters
ulBase is the base address of the PWM port.
ulChannel is the PWM channel.
ulIntType is the PWM channel interrupt type. Details please refer to xPWM Interrupt Type.
This function is to get the PWM interrupt flag of the PWM module.
The ulChannel parameter can be values: 0~7,when the ulBase is PWMA_BASE,the ulChannel parameter can be value 0~3,when the ulBase is PWMB_BASE,the ulChannel parameter can be value 4~7.
The ulIntType parameter can be values: xPWM_INT_PWM. Details please refer to 2.CoX Mandatory and CoX Non-mandatory
Note
None
Returns
None.
void xPWMIntCallbackInit (unsigned long ulBase, xtEventCallback xtPWMCallback)
Init interrupts callback for the PWM timer.
Parameters
xtPortCallback is callback for the PWM timer.
This function is to init interrupts callback for the PWM timer.
Returns
None.
© 2009-2011 by CooCox - visit http://www.coocox.org/