COX Shield: HD44780 Driver APIs
HD44780 Driver APIs
HD44780
API Refrence of HD44780 Driver.
Functions
void HD44780Init (void)
Init the HD44780 LCD Device.
void HD44780EntryModeSet (unsigned char ucCursorMoveDirection, xtBoolean bDisplayShift)
Set the the LCD entry mode.
void HD44780DisplayClear (void)
Clears the LCD display.
void HD44780DisplayOn (void)
Sets the entire LCD display on.
void HD44780DisplayOff (void)
Sets the entire LCD display off.
void HD44780CursorOn (xtBoolean bBlink)
Sets cursor on.
void HD44780CursorOff (void)
Sets cursor off.
void HD44780DisplayString (const char *pcString)
Display a string on the LCD.
void HD44780DisplayN (unsigned long n)
Display a decimal number on the LCD.
void HD44780Home (void)
Cursor back to Home.
void HD44780LocationSet (unsigned char x, unsigned char y)
Set the cursor location.
void HD44780CursorLeftMove (unsigned char n)
Move the cursor n unit to the left.
void HD44780CursorRightMove (unsigned char n)
Move the cursor n unit to the right.
void HD44780DisplayLeftShift (unsigned char n)
Shift the entire display n unit to the left.
void HD44780DisplayRightShift (unsigned char n)
Shift the entire display n unit to the right.
xtBoolean HD44780Busy (void)
determine if the HD44780 is busy.
void HD44780WriteCmd (unsigned char ucCmd)
void HD44780WriteData (unsigned char ucData)
unsigned long HD44780ReadState (void)
Read the state of the HD44780.
unsigned long HD44780ReadData (void)
Read data from the HD44780 DDRAM.
Detailed Description
API Refrence of HD44780 Driver.
Function Documentation
void HD44780Init (void)
Init the HD44780 LCD Device.
Parameters
None. This function is used to Init the HD44780 Device. It must be call before any other LCD function use.
It Open the pins's GPIO peripheral port, and config the pins type to GPIO output. Then config the LCD into the default state, clear the LCD and Open the display. Default A Blink cursor is set on. The LCD cursor move direction is config as increment default.
The HD44780 Initial state can be determined by the HD44780 Driver Configurtion.
Pins that used is determined by HD44780 Driver Pin Configurtion.
The inteface data length is determined by HD44780_INTERFACE_DATA_LEN.
The LCD display line is determined by HD44780_DISPLAY_LINE.
The LCD character font is determined by HD44780_CHARACTER_FONT.
Returns
None.
Definition at line 262 of file hd44780.c.
References HD44780_CHARACTER_FONT, HD44780_CMD_CLS, HD44780_CMD_DISPLAY_CTRL, HD44780_CMD_ENTRY_MODE_SET, HD44780_CMD_FUNCTION_SET, HD44780_DISPLAY_CTRL_B, HD44780_DISPLAY_CTRL_D, HD44780_E_DISABLE, HD44780_ENTRY_MODE_SET_ID_INC, HD44780_FUNCTION_SET_N_2, HD44780_INTERFACE_DATA_LEN, HD44780_PIN_D4, HD44780_PIN_D5, HD44780_PIN_D6, HD44780_PIN_D7, HD44780_PIN_E, HD44780_PIN_RS, HD44780_PIN_RW, HD44780Busy(), HD44780WriteCmd(), xGPIOSPinToPeripheralId, xGPIOSPinTypeGPIOOutput, xGPIOSPinWrite, and xSysCtlPeripheralEnable().
void HD44780EntryModeSet (unsigned char ucCursorMoveDirection, xtBoolean bDisplayShift)
Set the the LCD entry mode.
Parameters
ucCursorMoveDirection is the cursor move dirction.
bDisplayShift determines if the entire LCD shift when display a char.
In the HD44780Init() function, it has set a default entry mode. The cursor move direction is increment and no shift when display. You can change the setting with this function.
The parameter of ucCursorMoveDirection can be:
HD44780_MOVE_DIRECTION_INC - increment
HD44780_MOVE_DIRECTION_DEC - decrment.
The parameter of bDisplayShift cab be:
xtrue - display with shift.
xfalse - no shift wen display.
Returns
None.
Definition at line 348 of file hd44780.c.
References HD44780_CMD_ENTRY_MODE_SET, HD44780_ENTRY_MODE_SET_S, HD44780_MOVE_DIRECTION_DEC, HD44780_MOVE_DIRECTION_INC, HD44780Busy(), HD44780WriteCmd(), and xASSERT.
void HD44780DisplayClear (void)
Clears the LCD display.
Parameters
None. It clears the entire display, and set cursor to (0,0).
Returns
None.
Definition at line 375 of file hd44780.c.
References HD44780_CMD_CLS, HD44780Busy(), HD44780WriteCmd(), and xSysCtlDelay().
void HD44780DisplayOn (void)
Sets the entire LCD display on.
Parameters
None.
Returns
None.
Definition at line 396 of file hd44780.c.
References HD44780_CMD_DISPLAY_CTRL, HD44780_DISPLAY_CTRL_D, HD44780Busy(), and HD44780WriteCmd().
void HD44780DisplayOff (void)
Sets the entire LCD display off.
Parameters
None. It set the entire display to blank without changing the data that have been written into the LCD DDRAM.
Returns
None.
Definition at line 415 of file hd44780.c.
References HD44780_CMD_DISPLAY_CTRL, HD44780Busy(), and HD44780WriteCmd().
void HD44780CursorOn (xtBoolean bBlink)
Sets cursor on.
Parameters
bBlink determines the cursor style. xtrue is an blinking style, xfalse is an underline style.
Returns
None.
Definition at line 432 of file hd44780.c.
References HD44780_CMD_DISPLAY_CTRL, HD44780_DISPLAY_CTRL_B, HD44780_DISPLAY_CTRL_C, HD44780_DISPLAY_CTRL_D, HD44780Busy(), and HD44780WriteCmd().
void HD44780CursorOff (void)
Sets cursor off.
Parameters
None.
Returns
None.
Definition at line 452 of file hd44780.c.
References HD44780_CMD_DISPLAY_CTRL, HD44780_DISPLAY_CTRL_B, HD44780_DISPLAY_CTRL_C, HD44780_DISPLAY_CTRL_D, HD44780Busy(), and HD44780WriteCmd().
void HD44780DisplayString (const char * pcString)
Display a string on the LCD.
Parameters
pcString is a non-terminated string that to display.
Display a string on the cursor location.
Returns
None.
Definition at line 472 of file hd44780.c.
References HD44780Busy(), HD44780WriteData(), and xASSERT.
void HD44780DisplayN (unsigned long n)
Display a decimal number on the LCD.
Parameters
n is the number that to display.
Display a decimal number on the cursor location.
Returns
None.
Definition at line 498 of file hd44780.c.
References HD44780Busy(), and HD44780WriteData().
void HD44780Home (void)
Cursor back to Home.
Parameters
None. Sets Location at (0, 0). Also returns display from being shifted to original position. DDRAM contents remain unchanged.
Returns
None.
Definition at line 537 of file hd44780.c.
References HD44780_CMD_RETURN_HOME, HD44780Busy(), and HD44780WriteCmd().
void HD44780LocationSet (unsigned char x, unsigned char y)
Set the cursor location.
Parameters
x is the character index.
y is the line number.
The default location is (0,0). After set the location, the strings will display at the (x, y).
Returns
None.
Definition at line 557 of file hd44780.c.
References HD44780_CMD_DDRAM_ADDR_SET, HD44780_DISPLAY_CHARACTER, HD44780_DISPLAY_LINE, HD44780Busy(), HD44780WriteCmd(), and xASSERT.
void HD44780CursorLeftMove (unsigned char n)
Move the cursor n unit to the left.
Parameters
n is the unit number to move.
Returns
None.
Definition at line 586 of file hd44780.c.
References HD44780_CMD_CURSOR_DISPLAY_SHIFT, HD44780_CURSOR_DISPLAY_SHIFT_RL_L, HD44780_CURSOR_DISPLAY_SHIFT_SC_C, HD44780Busy(), and HD44780WriteCmd().
void HD44780CursorRightMove (unsigned char n)
Move the cursor n unit to the right.
Parameters
n is the unit number to move.
Returns
None.
Definition at line 613 of file hd44780.c.
References HD44780_CMD_CURSOR_DISPLAY_SHIFT, HD44780_CURSOR_DISPLAY_SHIFT_RL_R, HD44780_CURSOR_DISPLAY_SHIFT_SC_C, HD44780Busy(), and HD44780WriteCmd().
void HD44780DisplayLeftShift (unsigned char n)
Shift the entire display n unit to the left.
Parameters
n is the unit number to shift.
Returns
None.
Definition at line 639 of file hd44780.c.
References HD44780_CMD_CURSOR_DISPLAY_SHIFT, HD44780_CURSOR_DISPLAY_SHIFT_RL_L, HD44780_CURSOR_DISPLAY_SHIFT_SC_S, HD44780Busy(), and HD44780WriteCmd().
void HD44780DisplayRightShift (unsigned char n)
Shift the entire display n unit to the right.
Parameters
n is the unit number to shift.
Returns
None.
Definition at line 662 of file hd44780.c.
References HD44780_CMD_CURSOR_DISPLAY_SHIFT, HD44780_CURSOR_DISPLAY_SHIFT_RL_R, HD44780_CURSOR_DISPLAY_SHIFT_SC_S, HD44780Busy(), and HD44780WriteCmd().
xtBoolean HD44780Busy (void)
determine if the HD44780 is busy.
Parameters
None.
Returns
xtrue if the HD44780 is busy, xfalse if the HD44780 is idle.
Definition at line 215 of file hd44780.c.
References xfalse, and xSysCtlDelay().
Referenced by HD44780CursorLeftMove(), HD44780CursorOff(), HD44780CursorOn(), HD44780CursorRightMove(), HD44780DisplayClear(), HD44780DisplayLeftShift(), HD44780DisplayN(), HD44780DisplayOff(), HD44780DisplayOn(), HD44780DisplayRightShift(), HD44780DisplayString(), HD44780EntryModeSet(), HD44780Home(), HD44780Init(), and HD44780LocationSet().
void HD44780WriteCmd (unsigned char ucCmd)
Definition at line 177 of file hd44780.c.
References HD44780_RS_COMMAND, and HD44780Write().
Referenced by HD44780CursorLeftMove(), HD44780CursorOff(), HD44780CursorOn(), HD44780CursorRightMove(), HD44780DisplayClear(), HD44780DisplayLeftShift(), HD44780DisplayOff(), HD44780DisplayOn(), HD44780DisplayRightShift(), HD44780EntryModeSet(), HD44780Home(), HD44780Init(), and HD44780LocationSet().
void HD44780WriteData (unsigned char ucData)
Definition at line 183 of file hd44780.c.
References HD44780_RS_DATA, and HD44780Write().
Referenced by HD44780DisplayN(), and HD44780DisplayString().
unsigned long HD44780ReadState (void)
Read the state of the HD44780.
Parameters
None. The state info contains the busy flag and address count.
Returns
None.
Definition at line 200 of file hd44780.c.
References HD44780_RS_COMMAND, and HD44780Read().
unsigned long HD44780ReadData (void)
Read data from the HD44780 DDRAM.
Parameters
None.
Returns
data that have been read.
Definition at line 232 of file hd44780.c.
References HD44780_RS_DATA, and HD44780Read().
© 2009-2011 by CooCox - visit http://www.coocox.org/