COX Shield: MShied API
MShied API
motor Shield
Functions
void MS74HC595PinInit (void)
Init the 74HC595 connected pin.
void MS74HC595DataSend (unsigned char ucData)
Write data to 74HCT595N.
void MSDCMotorPWMInit (unsigned long ulBase, unsigned long ulChannel)
Init the PWM corresponding pins, and enable the corresponding port.
void MSDCMotorRun (unsigned long ulChannel, unsigned long ulDir)
Configure the PWM frecqurecy and output duty cycle.
void MSDCMotorSpeedSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulSpeed)
Set the DC motor speed.
void MSDCMotorStop (unsigned long ulChannel)
Disable the corresponding pwm output channel to stop the DC motor.
void MSStepMotorInit (unsigned long ulStepperNum)
Init the selected stepper number.
void MSStepsDelaySet (unsigned long ulDelay)
Set the step motor steps delay.
void MSStepMotorRun (unsigned long ulDir, unsigned long ulSteps)
Control the 42BYGH step motor roll direction and speed.
void MSStepMotorStop (void)
Stop the 42BYGH step motor.
void MSDelay (unsigned long ulDelay)
Dalay some time.
Detailed Description
Function Documentation
void MS74HC595PinInit (void)
Init the 74HC595 connected pin.
Note
The data will parral out.
Returns
None.
Definition at line 420 of file MotorShield.c.
References xGPIOSPinTypeGPIOOutput, and xGPIOSPinWrite.
Referenced by MSDCMotorPWMInit(), and MSStepMotorInit().
void MS74HC595DataSend (unsigned char ucData)
Write data to 74HCT595N.
Parameters
ucData is the serial in data.
Note
The data will parral out.
Returns
None.
Definition at line 451 of file MotorShield.c.
References xGPIOSPinWrite, and xSysCtlDelay().
Referenced by MSDCMotorPWMInit(), MSDCMotorRun(), MSDCMotorStop(), MSStepMotorRun(), and MSStepMotorStop().
void MSDCMotorPWMInit (unsigned long ulBase, unsigned long ulChannel)
Init the PWM corresponding pins, and enable the corresponding port.
Parameters
ulBase is the selected PWM.
ulChannel is the selected pwm channel.
The ulBase parameter can be one of the values: sPWMA_BASE, sPWMB_BASE.
The ulChannel parameter can be one of the values: MS_CHANNEL_PWM0A, MS_CHANNEL_PWM2A, MS_CHANNEL_PWM0B, PWM_CHANNEL_PWM2B.
Note
None.
Returns
None.
Definition at line 78 of file MotorShield.c.
References MS74HC595DataSend(), MS74HC595PinInit(), MS_CHANNEL_PWM0A, MS_CHANNEL_PWM0B, MS_CHANNEL_PWM2A, MS_CHANNEL_PWM2B, MS_PWMCNT_VALUE, MS_PWMDIV_VALUE, MS_PWMPSR_VALUE, xASSERT, xGPIOSPinToPeripheralId, xPWM_DEAD_ZONE_DIS, xPWM_FREQ_CONFIG, xPWM_OUTPUT_INVERTER_DIS, xPWM_TOGGLE_MODE, xPWMDutySet(), xPWMFrequencyConfig(), xPWMInitConfigure(), xPWMOutputEnable(), xPWMStart(), and xSysCtlPeripheralEnable2().
void MSDCMotorRun (unsigned long ulChannel, unsigned long ulDir)
Configure the PWM frecqurecy and output duty cycle.
Parameters
ulChannel is the selected pwm channel.
ulDir is the selection of Motor rev direction.
The ulChannel parameter can be one of the values: PWM_CHANNEL_PWM0A, PWM_CHANNEL_PWM2A, PWM_CHANNEL_PWM0B, PWM_CHANNEL_PWM2B.
The ulDir parameter can be one of the values: MS_RUN_FORWARD, MS_RUN_BACKWARD.
Note
None.
Returns
None.
Definition at line 211 of file MotorShield.c.
References MS74HC595DataSend(), MS_CHANNEL_PWM0A, MS_CHANNEL_PWM0B, MS_CHANNEL_PWM2A, MS_CHANNEL_PWM2B, MS_RUN_BACKWARD, MS_RUN_FORWARD, and xASSERT.
void MSDCMotorSpeedSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulSpeed)
Set the DC motor speed.
Parameters
ulBase is the selected PWM.
ulChannel is the selected pwm channel.
ulDir is the selection of Motor rev direction.
The ulBase parameter can be one of the values: sPWMA_BASE, sPWMB_BASE.
The ulChannel parameter can be one of the values: PWM_CHANNEL_PWM0A, PWM_CHANNEL_PWM2A, PWM_CHANNEL_PWM0B, PWM_CHANNEL_PWM2B.
The ulSpeed parameter can be values: Any values ,ulSpeed > 0 && ulSpeed < PWM module input clock.
Note
None.
Returns
None.
Definition at line 318 of file MotorShield.c.
References MS_CHANNEL_PWM0A, MS_CHANNEL_PWM0B, MS_CHANNEL_PWM2A, MS_CHANNEL_PWM2B, xASSERT, xPWMDutySet(), xPWMFrequencySet(), xPWMStart(), and xPWMStop().
void MSDCMotorStop (unsigned long ulChannel)
Disable the corresponding pwm output channel to stop the DC motor.
Parameters
ulChannel is the selected pwm channel.
The ulChannel parameter can be one of the values: MS_CHANNEL_PWM0A, MS_CHANNEL_PWM2A, MS_CHANNEL_PWM0B, MS_CHANNEL_PWM2B.
Note
None.
Returns
None.
Definition at line 367 of file MotorShield.c.
References MS74HC595DataSend(), MS_CHANNEL_PWM0A, MS_CHANNEL_PWM0B, MS_CHANNEL_PWM2A, MS_CHANNEL_PWM2B, and xASSERT.
void MSStepMotorInit (unsigned long ulStepperNum)
Init the selected stepper number.
Parameters
ulStepperNum is the selection of Stepper number.
The ulDir parameter can be one of the values: MS_STEPPER_NUM1, MS_STEPPER_NUM2.
Returns
None.
Definition at line 507 of file MotorShield.c.
References MS74HC595PinInit(), MS_STEPPER_NUM1, MS_STEPPER_NUM2, xASSERT, xGPIOSPinToPeripheralId, xGPIOSPinTypeGPIOOutput, xGPIOSPinWrite, and xSysCtlPeripheralEnable2().
void MSStepsDelaySet (unsigned long ulDelay)
Set the step motor steps delay.
Parameters
ulDelay is the steps delay ms.
Returns
None.
Definition at line 565 of file MotorShield.c.
void MSStepMotorRun (unsigned long ulDir, unsigned long ulSteps)
Control the 42BYGH step motor roll direction and speed.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port.
ulDir is the selection of Step Motor running direction.
ulSteps is the motor rev step number.
The ulDir parameter can be one of the values: MS_RUN_FORWARD, MS_RUN_BACKWARD.
Note
The 42BYGH step motor is drivered by ladyada mshield IC1. The red wire connect to 1A(red <-> 1A), and (green <-> 2A), (yellow <-> 3A), (blue <-> 4A).
Returns
None.
Definition at line 590 of file MotorShield.c.
References MS74HC595DataSend(), MS_RUN_BACKWARD, MS_RUN_FORWARD, MSDelay(), and xASSERT.
void MSStepMotorStop (void)
Stop the 42BYGH step motor.
Parameters
None
Returns
None.
Definition at line 633 of file MotorShield.c.
References MS74HC595DataSend().
void MSDelay (unsigned long ulDelay)
Dalay some time.
Parameters
ulDelay is the delay number of ms.
Returns
None.
Definition at line 648 of file MotorShield.c.
References MS_DELAY_CHANNEL, MS_DELAY_CLKSRC, MS_DELAY_TIMER, xSysCtlPeripheralClockSourceSet(), xSysCtlPeripheralDisable2(), xSysCtlPeripheralEnable2(), xTIMER_INT_MATCH, xTIMER_MODE_PERIODIC, xTimerInitConfig(), xTimerIntEnable(), xTimerStart(), xTimerStatusGet(), and xTimerStop().
Referenced by MSStepMotorRun().
© 2009-2011 by CooCox - visit http://www.coocox.org/