COX Shield: xCORE API
xCORE API
xCORE
Cortex-M0/M3 Core peripheral(CPU, NVIC, Systick) API reference.
Functions
unsigned long xCPUcpsid (void)
Wrapper function for the cpsid instruction.
unsigned long xCPUcpsie (void)
Wrapper function for the cpsie instruction.
unsigned long xCPUprimask (void)
Wrapper function returning the state of primask (indicating whether interrupts are enabled or disabled).
void xCPUwfi (void)
Wrapper function for the wfi instruction.
unsigned long xCPUbasepriGet (void)
Wrapper function for reading the basepri register.
void xCPUbasepriSet (unsigned long ulNewBasepri)
Wrapper function for writing the BASEPRI register.
void xCPUpspSet (unsigned long ulNewPspStack)
Wrapper function for writing the psp register.
unsigned long xCPUpspGet (void)
Wrapper function for reading the psp register.
void xCPUmspSet (unsigned long ulNewMspStack)
Wrapper function for writing the msp register.
unsigned long xCPUmspGet (void)
Wrapper function for reading the msp register.
xtBoolean xIntMasterEnable (void)
Enables the processor interrupt.
xtBoolean xIntMasterDisable (void)
Disables the processor interrupt.
void xIntPriorityGroupingSet (unsigned long ulBits)
unsigned long xIntPriorityGroupingGet (void)
void xIntPrioritySet (unsigned long ulInterrupt, unsigned char ucPriority)
Sets the priority of an interrupt.
long xIntPriorityGet (unsigned long ulInterrupt)
Gets the priority of an interrupt.
void xIntEnable (unsigned long ulInterrupt)
Enables an interrupt.
void xIntDisable (unsigned long ulInterrupt)
Disables an interrupt.
void xIntPendSet (unsigned long ulInterrupt)
Pends an interrupt.
void xIntPendClear (unsigned long ulInterrupt)
Unpends an interrupt.
void xIntPriorityMaskSet (unsigned long ulPriorityMask)
Sets the priority masking level.
unsigned long xIntPriorityMaskGet (void)
Gets the priority masking level.
void xSysTickEnable (void)
Enables the SysTick counter.
void xSysTickDisable (void)
Disables the SysTick counter.
void xSysTickIntEnable (void)
Enables the SysTick interrupt.
void xSysTickIntDisable (void)
Disables the SysTick interrupt.
void xSysTickPeriodSet (unsigned long ulPeriod)
Sets the period of the SysTick counter.
unsigned long xSysTickPeriodGet (void)
Gets the period of the SysTick counter.
unsigned long xSysTickValueGet (void)
Gets the current value of the SysTick counter.
void xSysTickPendSet (void)
Set the SysTick pending.
void xSysTickPendClr (void)
Clear the SysTick pending.
void xPendSVPendSet (void)
Set the PendSV pending.
void xPendSVPendClr (void)
Clear the PendSV pending.
Detailed Description
Cortex-M0/M3 Core peripheral(CPU, NVIC, Systick) API reference.
Function Documentation
unsigned long xCPUcpsid (void)
Wrapper function for the cpsid instruction.
Returns
Returns the state of primask on entry.
Referenced by xIntMasterDisable().
unsigned long xCPUcpsie (void)
Wrapper function for the cpsie instruction.
Returns
Returns the state of primask on entry.
Referenced by xIntMasterEnable().
unsigned long xCPUprimask (void)
Wrapper function returning the state of primask (indicating whether interrupts are enabled or disabled).
Returns
Returns the state of primask.
void xCPUwfi (void)
Wrapper function for the wfi instruction.
Returns
None.
unsigned long xCPUbasepriGet (void)
Wrapper function for reading the basepri register.
Returns
Returns the value of basepri register.
Referenced by xIntPriorityMaskGet().
void xCPUbasepriSet (unsigned long ulNewBasepri)
Wrapper function for writing the BASEPRI register.
Parameters
ulNewBasepri is the new BASEPRI value.
Returns
None.
Referenced by xIntPriorityMaskSet().
void xCPUpspSet (unsigned long ulNewPspStack)
Wrapper function for writing the psp register.
Parameters
ulNewPspStack is the new psp register value.
Returns
None.
unsigned long xCPUpspGet (void)
Wrapper function for reading the psp register.
Returns
Returns the value of psp register.
void xCPUmspSet (unsigned long ulNewMspStack)
Wrapper function for writing the msp register.
Parameters
ulNewMspStack is the new msp value.
Returns
None.
unsigned long xCPUmspGet (void)
Wrapper function for reading the msp register.
Returns
Returns the value of msp register.
xtBoolean xIntMasterEnable (void)
Enables the processor interrupt.
Allows the processor to respond to interrupts. This does not affect the set of interrupts enabled in the interrupt controller; it just gates the single interrupt from the controller to the processor.
Returns
Returns true if interrupts were disabled when the function was called or false if they were initially enabled.
Definition at line 604 of file xcore.c.
References xCPUcpsie().
xtBoolean xIntMasterDisable (void)
Disables the processor interrupt.
Prevents the processor from receiving interrupts. This does not affect the set of interrupts enabled in the interrupt controller; it just gates the single interrupt from the controller to the processor.
Returns
Returns true if interrupts were already disabled when the function was called or false if they were initially enabled.
Definition at line 625 of file xcore.c.
References xCPUcpsid().
void xIntPriorityGroupingSet (unsigned long ulBits)
unsigned long xIntPriorityGroupingGet (void)
void xIntPrioritySet (unsigned long ulInterrupt, unsigned char ucPriority)
Sets the priority of an interrupt.
Parameters
ulInterrupt specifies the interrupt in question.
ucPriority specifies the priority of the interrupt.
This function is used to set the priority of an interrupt. When multiple interrupts are asserted simultaneously, the ones with the highest priority are processed before the lower priority interrupts. Smaller numbers correspond to higher interrupt priorities; priority 0 is the highest interrupt priority.
The hardware priority mechanism will only look at the upper N bits of the priority level (where N is 3 for the Stellaris family), so any prioritization must be performed in those bits. The remaining bits can be used to sub-prioritize the interrupt sources, and may be used by the hardware priority mechanism on a future part. This arrangement allows priorities to migrate to different NVIC implementations without changing the gross prioritization of the interrupts.
Returns
None.
Definition at line 658 of file xcore.c.
References xASSERT, and xHWREG.
long xIntPriorityGet (unsigned long ulInterrupt)
Gets the priority of an interrupt.
Parameters
ulInterrupt specifies the interrupt in question.
This function gets the priority of an interrupt. See xIntPrioritySet() for a definition of the priority value.
Returns
Returns the interrupt priority, or -1 if an invalid interrupt was specified.
Definition at line 690 of file xcore.c.
References xASSERT, and xHWREG.
void xIntEnable (unsigned long ulInterrupt)
Enables an interrupt.
Parameters
ulInterrupt specifies the interrupt to be enabled.
The specified interrupt is enabled in the interrupt controller. Other enables for the interrupt (such as at the peripheral level) are unaffected by this function.
Returns
None.
Definition at line 718 of file xcore.c.
References NVIC_EN0, NVIC_ST_CTRL, NVIC_ST_CTRL_INTEN, NVIC_SYS_HND_CTRL, NVIC_SYS_HND_CTRL_BUS, NVIC_SYS_HND_CTRL_MEM, NVIC_SYS_HND_CTRL_USAGE, xASSERT, xFAULT_BUS, xFAULT_MPU, xFAULT_SYSTICK, xFAULT_USAGE, and xHWREG.
Referenced by SensorShieldInit().
void xIntDisable (unsigned long ulInterrupt)
Disables an interrupt.
Parameters
ulInterrupt specifies the interrupt to be disabled.
The specified interrupt is disabled in the interrupt controller. Other enables for the interrupt (such as at the peripheral level) are unaffected by this function.
Returns
None.
Definition at line 779 of file xcore.c.
References NVIC_DIS0, NVIC_ST_CTRL, NVIC_ST_CTRL_INTEN, NVIC_SYS_HND_CTRL, NVIC_SYS_HND_CTRL_BUS, NVIC_SYS_HND_CTRL_MEM, NVIC_SYS_HND_CTRL_USAGE, xASSERT, xFAULT_BUS, xFAULT_MPU, xFAULT_SYSTICK, xFAULT_USAGE, and xHWREG.
void xIntPendSet (unsigned long ulInterrupt)
Pends an interrupt.
Parameters
ulInterrupt specifies the interrupt to be pended.
The specified interrupt is pended in the interrupt controller. This will cause the interrupt controller to execute the corresponding interrupt handler at the next available time, based on the current interrupt state priorities. For example, if called by a higher priority interrupt handler, the specified interrupt handler will not be called until after the current interrupt handler has completed execution. The interrupt must have been enabled for it to be called.
Returns
None.
Definition at line 844 of file xcore.c.
References NVIC_INT_CTRL, NVIC_INT_CTRL_NMI_SET, NVIC_INT_CTRL_PEND_SV, NVIC_INT_CTRL_PENDSTSET, NVIC_PEND0, xASSERT, xFAULT_NMI, xFAULT_PENDSV, xFAULT_SYSTICK, and xHWREG.
void xIntPendClear (unsigned long ulInterrupt)
Unpends an interrupt.
Parameters
ulInterrupt specifies the interrupt to be unpended.
The specified interrupt is unpended in the interrupt controller. This will cause any previously generated interrupts that have not been handled yet (due to higher priority interrupts or the interrupt no having been enabled yet) to be discarded.
Returns
None.
Definition at line 899 of file xcore.c.
References NVIC_INT_CTRL, NVIC_INT_CTRL_PENDSTCLR, NVIC_INT_CTRL_UNPEND_SV, NVIC_UNPEND0, xASSERT, xFAULT_PENDSV, xFAULT_SYSTICK, and xHWREG.
void xIntPriorityMaskSet (unsigned long ulPriorityMask)
Sets the priority masking level.
Parameters
ulPriorityMask is the priority level that will be masked.
This function sets the interrupt priority masking level so that all interrupts at the specified or lesser priority level is masked. This can be used to globally disable a set of interrupts with priority below a predetermined threshold. A value of 0 disables priority masking.
Smaller numbers correspond to higher interrupt priorities. So for example a priority level mask of 4 will allow interrupts of priority level 0-3, and interrupts with a numerical priority of 4 and greater will be blocked.
The hardware priority mechanism will only look at the upper N bits of the priority level (where N is 3 for the Stellaris family), so any prioritization must be performed in those bits.
Returns
None.
Definition at line 956 of file xcore.c.
References xCPUbasepriSet().
unsigned long xIntPriorityMaskGet (void)
Gets the priority masking level.
This function gets the current setting of the interrupt priority masking level. The value returned is the priority level such that all interrupts of that and lesser priority are masked. A value of 0 means that priority masking is disabled.
Smaller numbers correspond to higher interrupt priorities. So for example a priority level mask of 4 will allow interrupts of priority level 0-3, and interrupts with a numerical priority of 4 and greater will be blocked.
The hardware priority mechanism will only look at the upper N bits of the priority level (where N is 3 for the Stellaris family), so any prioritization must be performed in those bits.
Returns
Returns the value of the interrupt priority level mask.
Definition at line 982 of file xcore.c.
References xCPUbasepriGet().
void xSysTickEnable (void)
Enables the SysTick counter.
This will start the SysTick counter. If an interrupt handler has been registered, it will be called when the SysTick counter rolls over.
Note
Calling this function will cause the SysTick counter to (re)commence counting from its current value. The counter is not automatically reloaded with the period as specified in a previous call to xSysTickPeriodSet(). If an immediate reload is required, the NVIC_ST_CURRENT register must be written to force this. Any write to this register clears the SysTick counter to 0 and will cause a reload with the supplied period on the next clock.
Returns
None.
Definition at line 1006 of file xcore.c.
References NVIC_ST_CTRL, NVIC_ST_CTRL_CLK_SRC, NVIC_ST_CTRL_ENABLE, and xHWREG.
void xSysTickDisable (void)
Disables the SysTick counter.
This will stop the SysTick counter. If an interrupt handler has been registered, it will no longer be called until SysTick is restarted.
Returns
None.
Definition at line 1025 of file xcore.c.
References NVIC_ST_CTRL, NVIC_ST_CTRL_ENABLE, and xHWREG.
void xSysTickIntEnable (void)
Enables the SysTick interrupt.
This function will enable the SysTick interrupt, allowing it to be reflected to the processor.
Note
The SysTick interrupt handler does not need to clear the SysTick interrupt source as this is done automatically by NVIC when the interrupt handler is called.
Returns
None.
Definition at line 1048 of file xcore.c.
References NVIC_ST_CTRL, NVIC_ST_CTRL_INTEN, and xHWREG.
void xSysTickIntDisable (void)
Disables the SysTick interrupt.
This function will disable the SysTick interrupt, preventing it from being reflected to the processor.
Returns
None.
Definition at line 1067 of file xcore.c.
References NVIC_ST_CTRL, NVIC_ST_CTRL_INTEN, and xHWREG.
void xSysTickPeriodSet (unsigned long ulPeriod)
Sets the period of the SysTick counter.
Parameters
ulPeriod is the number of clock ticks in each period of the SysTick counter; must be between 1 and 16,777,216, inclusive.
This function sets the rate at which the SysTick counter wraps; this equates to the number of processor clocks between interrupts.
Note
Calling this function does not cause the SysTick counter to reload immediately. If an immediate reload is required, the NVIC_ST_CURRENT register must be written. Any write to this register clears the SysTick counter to 0 and will cause a reload with the ulPeriod supplied here on the next clock after the SysTick is enabled.
Returns
None.
Definition at line 1095 of file xcore.c.
References NVIC_ST_RELOAD, xASSERT, and xHWREG.
unsigned long xSysTickPeriodGet (void)
Gets the period of the SysTick counter.
This function returns the rate at which the SysTick counter wraps; this equates to the number of processor clocks between interrupts.
Returns
Returns the period of the SysTick counter.
Definition at line 1119 of file xcore.c.
References NVIC_ST_RELOAD, and xHWREG.
unsigned long xSysTickValueGet (void)
Gets the current value of the SysTick counter.
This function returns the current value of the SysTick counter; this will be a value between the period - 1 and zero, inclusive.
Returns
Returns the current value of the SysTick counter.
Definition at line 1138 of file xcore.c.
References NVIC_ST_CURRENT, and xHWREG.
void xSysTickPendSet (void)
Set the SysTick pending.
This function will Set the SysTick pending.
Returns
None.
Definition at line 1156 of file xcore.c.
References NVIC_INT_CTRL, NVIC_INT_CTRL_PENDSTSET, and xHWREG.
void xSysTickPendClr (void)
Clear the SysTick pending.
This function will Clear the SysTick pending.
Returns
None.
Definition at line 1174 of file xcore.c.
References NVIC_INT_CTRL, NVIC_INT_CTRL_PENDSTCLR, and xHWREG.
void xPendSVPendSet (void)
Set the PendSV pending.
This function will Set the PendSV pending.
Returns
None.
Definition at line 1192 of file xcore.c.
References NVIC_INT_CTRL, NVIC_INT_CTRL_PEND_SV, and xHWREG.
void xPendSVPendClr (void)
Clear the PendSV pending.
This function will Clear the PendSV pending.
Returns
None.
Definition at line 1210 of file xcore.c.
References NVIC_INT_CTRL, NVIC_INT_CTRL_UNPEND_SV, and xHWREG.
© 2009-2011 by CooCox - visit http://www.coocox.org/