COX Shield: xUART API
xUART API
xUART
UART API Reference.
Functions
void xUARTConfigSet (unsigned long ulBase, unsigned long ulBaud, unsigned long ulConfig)
Sets the configuration of a UART.
void xUARTEnable (unsigned long ulBase, unsigned long ulBlock)
Enables transmitting or receiving.
void xUARTDisable (unsigned long ulBase, unsigned long ulBlock)
Disables transmitting or receiving.
void xUARTFIFOEnable (unsigned long ulBase)
Enables the transmit and receive FIFOs.
void xUARTFIFODisable (unsigned long ulBase)
Disables the transmit and receive FIFOs.
void xUARTFIFORxLevelSet (unsigned long ulBase, unsigned long ulRxLevel)
Sets the Rx FIFO level at which interrupts are generated.
void xUARTCharsAvail (unsigned long ulBase)
Determines if there are any characters in the receive FIFO.
void xUARTSpaceAvail (unsigned long ulBase)
Determines if there is any space in the transmit FIFO.
void xUARTCharGetNonBlocking (unsigned long ulBase)
Receives a character from the specified port.
void xUARTCharGet (unsigned long ulBase)
Waits for a character from the specified port.
void xUARTCharPutNonBlocking (unsigned long ulBase, unsigned char ucData)
Sends a character to the specified port.
void xUARTCharPut (unsigned long ulBase, unsigned char ucData)
Waits to send a character from the specified port.
void xUARTBusy (unsigned long ulBase)
Determines whether the UART transmitter is busy or not.
void xUARTIntEnable (unsigned long ulBase, unsigned long ulIntFlags)
Enables individual UART interrupt sources.
void xUARTIntCallbackInit (unsigned long ulBase, xtEventCallback xtUARTCallback)
Init interrupts callback for the specified UART Port.
void xUARTIntDisable (unsigned long ulBase, unsigned long ulIntFlags)
Disables individual UART interrupt sources.
void xUARTRxErrorGet (unsigned long ulBase)
Gets current receiver errors.
void xUARTRxErrorClear (unsigned long ulBase)
Clears all reported receiver errors.
void xUARTModemControlSet (unsigned long ulBase, unsigned long ulControl)
Sets the states of the DTR and/or RTS modem control signals.
void xUARTModemControlClear (unsigned long ulBase, unsigned long ulControl)
Clears the states of the DTR and/or RTS modem control signals.
void xUARTModemControlGet (unsigned long ulBase, unsigned long ulControl)
Gets the states of the DTR and RTS modem control signals.
void xUARTModemStatusGet (unsigned long ulBase)
Gets the states of the RI, DCD, DSR and CTS modem status signals.
void xUARTFlowControlSet (unsigned long ulBase, unsigned long ulMode)
Sets the UART hardware flow control mode to be used.
void xUARTFlowControlGet (unsigned long ulBase)
Returns the UART hardware flow control mode currently in use.
void xUARTIrDAConfig (unsigned long ulBase, unsigned long ulBaud, unsigned long ulConfig, unsigned long ulMode)
Enables SIR (IrDA) mode on the specified UART.
void xUARTIrDAEnable (ulBase)
Enables SIR (IrDA) mode on the specified UART.
void xUARTIrDADisable (unsigned long ulBase)
Disables SIR (IrDA) mode on the specified UART.
void xUARTLINConfig (unsigned long ulBase, unsigned long ulBaud, unsigned long ulConfig)
Open LIN mode on the specified UART.
void xUARTLINEnable (unsigned long ulBase)
Enables LIN Function mode on the specified UART.
void xUARTLINDisable (unsigned long ulBase)
Disables LIN Function mode on the specified UART.
Detailed Description
UART API Reference.
@section xUART_Exported_APIs_Port CoX Port Details
@verbatim
//! +---------------------—+-------------—+-----—+ //! |xUART API | CoX | NUC1xx | //! |---------------------—|-------------—|-----—| //! |xUARTConfigSet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTEnable | Mandatory | N | //! |---------------------—|-------------—|-----—| //! |xUARTDisable | Mandatory | N | //! |---------------------—|-------------—|-----—| //! |xUARTFIFOEnable | Non-Mandatory | N | //! |---------------------—|-------------—|-----—| //! |xUARTFIFODisable | Non-Mandatory | N | //! |---------------------—|-------------—|-----—| //! |xUARTFIFORxLevelSet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTCharsAvail | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTSpaceAvail | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTCharGetNonBlocking | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTCharGet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTCharPutNonBlocking | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTCharPut | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTBusy | Non-Mandatory | N | //! |---------------------—|-------------—|-----—| //! |xUARTIntEnable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTIntCallbackInit | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTIntDisable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTRxErrorGet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTRxErrorClear | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTModemControlSet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTModemControlClear | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTModemControlGet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTModemStatusGet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTFlowControlSet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTFlowControlGet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTIrDAConfig | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTIrDAEnable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTIrDADisable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTLINConfig | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTLINEnable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xUARTLINDisable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //!
Function Documentation
void xUARTConfigSet (unsigned long ulBase, unsigned long ulBaud, unsigned long ulConfig)
Sets the configuration of a UART.
Parameters
ulBase is the base address of the UART port.
ulBaud is the desired baud rate.
ulConfig is the data format for the port (number of data bits, number of stop bits, and parity).
This function configures the UART for operation in the specified data format. The baud rate is provided in the ulBaud parameter and the data format in the ulConfig parameter.
The ulConfig parameter is the logical OR of three values: the number of data bits, the number of stop bits, and the parity. UART_CONFIG_WLEN_8, xUART_CONFIG_WLEN_7, xUART_CONFIG_WLEN_6, and xUART_CONFIG_WLEN_5 select from eight to five data bits per byte (respectively). xUART_CONFIG_STOP_1 and xUART_CONFIG_STOP_2 select one or two stop bits (respectively). xUART_CONFIG_PAR_NONE, xUART_CONFIG_PAR_EVEN, xUART_CONFIG_PAR_ODD, xUART_CONFIG_PAR_ONE, and xUART_CONFIG_PAR_ZERO select the parity mode (no parity bit, even parity bit, odd parity bit, parity bit always one, and parity bit always zero, respectively).
Returns
None.
Referenced by SensorShieldInit().
void xUARTEnable (unsigned long ulBase, unsigned long ulBlock)
Enables transmitting or receiving.
Parameters
ulBase is the base address of the UART port.
ulBlock is the block to enable. it is the logical OR of these values: xUART_BLOCK_TX, xUART_BLOCK_RX.
Sets the UARTEN, or TXE or RXE bits.
Note
Do nothing in UART,In IrDA and LIN mode will set the Tx or Rx enable
Returns
None.
void xUARTDisable (unsigned long ulBase, unsigned long ulBlock)
Disables transmitting or receiving.
Parameters
ulBase is the base address of the UART port.
ulBlock is the block to disable. it is the logical OR of these values: xUART_BLOCK_UART, xUART_BLOCK_TX, xUART_BLOCK_RX.
Waits for the end ofransmission of the current character, Clears the UARTEN or TXE or RXE bits.
Note
Do nothing in NUVOTON
Returns
None.
void xUARTFIFOEnable (unsigned long ulBase)
Enables the transmit and receive FIFOs.
Parameters
ulBase is the base address of the UART port.
This functions enables the transmit and receive FIFOs in the UART.
Note
Do nothing in NUVOTON
Returns
None.
void xUARTFIFODisable (unsigned long ulBase)
Disables the transmit and receive FIFOs.
Parameters
ulBase is the base address of the UART port.
This functions disables the transmit and receive FIFOs in the UART.
Note
Do nothing in NUVOTON
Returns
None.
void xUARTFIFORxLevelSet (unsigned long ulBase, unsigned long ulRxLevel)
Sets the Rx FIFO level at which interrupts are generated.
Parameters
ulBase is the base address of the UART port.
ulRxLevel is the receive FIFO interrupt level, specified as one of xUART_FIFO_RX_1, xUART_FIFO_RX_4, xUART_FIFO_RX_8, xUART_FIFO_RX_14, xUART_FIFO_RX_30, xUART_FIFO_RX_46, or xUART_FIFO_RX_62.
This function sets the FIFO level at which receive interrupts are generated.
Returns
None.
void xUARTCharsAvail (unsigned long ulBase)
Determines if there are any characters in the receive FIFO.
Parameters
ulBase is the base address of the UART port.
This function returns a flag indicating whether or not there is data available in the receive FIFO.
Returns
Returns true if there is data in the receive FIFO or false if there is no data in the receive FIFO.
void xUARTSpaceAvail (unsigned long ulBase)
Determines if there is any space in the transmit FIFO.
Parameters
ulBase is the base address of the UART port.
This function returns a flag indicating whether or not there is space available in the transmit FIFO.
Returns
Returns true if there is space available in the transmit FIFO or false if there is no space available in the transmit FIFO.
void xUARTCharGetNonBlocking (unsigned long ulBase)
Receives a character from the specified port.
Parameters
ulBase is the base address of the UART port.
Gets a character from the receive FIFO for the specified port.
This function replaces the original UARTCharNonBlockingGet() API and performs the same actions. A macro is provided in uart.h to map the original API to this API.
Returns
Returns the character read from the specified port, cast as a long. A -1 is returned if there are no characters present in the receive FIFO. The UARTCharsAvail() function should be called before attempting to call this function.
void xUARTCharGet (unsigned long ulBase)
Waits for a character from the specified port.
Parameters
ulBase is the base address of the UART port.
Gets a character from the receive FIFO for the specified port. If there are no characters available, this function waits until a character is received before returning.
Returns
Returns the character read from the specified port, cast as a long.
Referenced by SensorShieldUARTBufferGet().
void xUARTCharPutNonBlocking (unsigned long ulBase, unsigned char ucData)
Sends a character to the specified port.
Parameters
ulBase is the base address of the UART port.
ucData is the character to be transmitted.
Writes the character ucData to the transmit FIFO for the specified port. This function does not block, so if there is no space available, then a false is returned, and the application must retry the function later.
This function replaces the original UARTCharNonBlockingPut() API and performs the same actions. A macro is provided in uart.h to map the original API to this API.
Returns
Returns true if the character was successfully placed in the transmit FIFO or false if there was no space available in the transmit FIFO.
void xUARTCharPut (unsigned long ulBase, unsigned char ucData)
Waits to send a character from the specified port.
Parameters
ulBase is the base address of the UART port.
ucData is the character to be transmitted.
Sends the character ucData to the transmit FIFO for the specified port. If there is no space available in the transmit FIFO, this function waits until there is space available before returning.
Returns
None.
Referenced by SensorShieldUARTBufferPut().
void xUARTBusy (unsigned long ulBase)
Determines whether the UART transmitter is busy or not.
Parameters
ulBase is the base address of the UART port.
Allows the caller to determine whether all transmitted bytes have cleared the transmitter hardware. If false is returned, the transmit FIFO is empty and all bits of the last transmitted character, including all stop bits, have left the hardware shift register.
Returns
Returns true if the UART is transmitting or false if all transmissions are complete.
void xUARTIntEnable (unsigned long ulBase, unsigned long ulIntFlags)
Enables individual UART interrupt sources.
Parameters
ulBase is the base address of the UART port.
ulIntFlags is the bit mask of the interrupt sources to be enabled.
Enables the indicated UART interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The ulIntFlags parameter is the logical OR of any of the following:
xUART_INT_ERROR - All Error interrupt
xUART_INT_RT - Receive Timeout interrupt
xUART_INT_TX - Transmit interrupt
xUART_INT_RX - Receive interrupt
Returns
None.
void xUARTIntCallbackInit (unsigned long ulBase, xtEventCallback xtUARTCallback)
Init interrupts callback for the specified UART Port.
Parameters
ulPort is the base address of the UART port.
xtI2CCallback is callback for the specified UART Port.
Init interrupts callback for the specified UART Port.
Returns
None.
void xUARTIntDisable (unsigned long ulBase, unsigned long ulIntFlags)
Disables individual UART interrupt sources.
Parameters
ulBase is the base address of the UART port.
ulIntFlags is the bit mask of the interrupt sources to be disabled.
Disables the indicated UART interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The ulIntFlags parameter has the same definition as the ulIntFlags parameter to UARTIntEnable().
xUART_INT_ERROR - All Error interrupt
xUART_INT_RT - Receive Timeout interrupt
xUART_INT_TX - Transmit interrupt
xUART_INT_RX - Receive interrupt
Returns
None.
void xUARTRxErrorGet (unsigned long ulBase)
Gets current receiver errors.
Parameters
ulBase is the base address of the UART port.
This function returns the current state of each of the 4 receiver error sources. The returned errors are equivalent to the four error bits returned via the previous call to UARTCharGet() or UARTCharGetNonBlocking() with the exception that the overrun error is set immediately the overrun occurs rather than when a character is next read.
Returns
Returns a logical OR combination of the receiver error flags, xUART_RXERROR_FRAMING, xUART_RXERROR_PARITY, xUART_RXERROR_BREAK and xUART_RXERROR_OVERRUN.
void xUARTRxErrorClear (unsigned long ulBase)
Clears all reported receiver errors.
Parameters
ulBase is the base address of the UART port.
This function is used to clear all receiver error conditions reported via UARTRxErrorGet(). If using the overrun, framing error, parity error or break interrupts, this function must be called after clearing the interrupt to ensure that later errors of the same type trigger another interrupt.
Returns
None.
void xUARTModemControlSet (unsigned long ulBase, unsigned long ulControl)
Sets the states of the DTR and/or RTS modem control signals.
Parameters
ulBase is the base address of the UART port.
ulControl is a bit-mapped flag indicating which modem control bits should be set.
Sets the states of the DTR or RTS modem handshake outputs from the UART.
The ulControl parameter is the logical OR of any of the following:
xUART_OUTPUT_RTS - The Modem Control RTS signal
Note
It is not available on UART2.
Returns
None.
void xUARTModemControlClear (unsigned long ulBase, unsigned long ulControl)
Clears the states of the DTR and/or RTS modem control signals.
Parameters
ulBase is the base address of the UART port.
ulControl is a bit-mapped flag indicating which modem control bits should be set.
Clears the states of the DTR or RTS modem handshake outputs from the UART.
The ulControl parameter is the logical OR of any of the following:
xUART_OUTPUT_RTS - The Modem Control RTS signal
Note
It is not available on UART2
Returns
None.
void xUARTModemControlGet (unsigned long ulBase, unsigned long ulControl)
Gets the states of the DTR and RTS modem control signals.
Parameters
ulBase is the base address of the UART port.
Returns the current states of each of the two UART modem control signals, DTR and RTS.
Note
It is not available on UART2
Returns
Returns the states of the handshake output signals. This will be a logical logical OR combination of values xUART_OUTPUT_RTS where the presence of each flag indicates that the associated signal is asserted.
void xUARTModemStatusGet (unsigned long ulBase)
Gets the states of the RI, DCD, DSR and CTS modem status signals.
Parameters
ulBase is the base address of the UART port.
Returns the current states of each of the four UART modem status signals, RI, DCD, DSR and CTS.
Note
It is not available on UART2
Returns
Returns the states of the handshake output signals. This will be a logical logical OR combination of values xUART_INPUT_CTS, where the presence of each flag indicates that the associated signal is asserted.
void xUARTFlowControlSet (unsigned long ulBase, unsigned long ulMode)
Sets the UART hardware flow control mode to be used.
Parameters
ulBase is the base address of the UART port.
ulMode indicates the flow control modes to be used. This is a logical OR combination of values xUART_FLOWCONTROL_TX and xUART_FLOWCONTROL_RX to enable hardware transmit (CTS) and receive (RTS) flow control or xUART_FLOWCONTROL_NONE to disable hardware flow control.
Sets the required hardware flow control modes. If ulMode contains flag xUART_FLOWCONTROL_TX, data is only transmitted if the incoming CTS signal is asserted. If ulMode contains flag xUART_FLOWCONTROL_RX, the RTS output is controlled by the hardware and is asserted only when there is space available in the receive FIFO. If no hardware flow control is required, xUART_FLOWCONTROL_NONE should be passed.
Note
The availability of hardware flow control varies with the Stellaris part and UART in use. Please consult the datasheet for the part you are using to determine whether this support is available.
Returns
None.
void xUARTFlowControlGet (unsigned long ulBase)
Returns the UART hardware flow control mode currently in use.
Parameters
ulBase is the base address of the UART port.
Returns the current hardware flow control mode.
Note
The availability of hardware flow control varies with the Stellaris part and UART in use. Please consult the datasheet for the part you are using to determine whether this support is available.
Returns
Returns the current flow control mode in use. This is a logical OR combination of values xUART_FLOWCONTROL_TX if transmit (CTS) flow control is enabled and xUART_FLOWCONTROL_RX if receive (RTS) flow control is in use. If hardware flow control is disabled, xUART_FLOWCONTROL_NONE will be returned.
void xUARTIrDAConfig (unsigned long ulBase, unsigned long ulBaud, unsigned long ulConfig, unsigned long ulMode)
Enables SIR (IrDA) mode on the specified UART.
Parameters
ulBase is the base address of the UART port.
ulBaud is the desired baud rate.
ulConfig is the data format for the port (number of data bits, number of stop bits, and parity).
ulMode is the IrDA mode.
This function configures the UART IrDA for operation in the specified data format. The baud rate is provided in the ulBaud parameter, the data format in the ulConfig parameter, and the ulMode is provided in the ulMode parameter.
The ulConfig parameter is the logical OR of three values: the number of data bits, the number of stop bits, and the parity. xUART_CONFIG_WLEN_8, xUART_CONFIG_WLEN_7, xUART_CONFIG_WLEN_6, and xUART_CONFIG_WLEN_5 select from eight to five data bits per byte (respectively). UART_CONFIG_STOP_1 and xUART_CONFIG_STOP_2 select one or two stop bits (respectively). xUART_CONFIG_PAR_NONE, xUART_CONFIG_PAR_EVEN, xUART_CONFIG_PAR_ODD, xUART_CONFIG_PAR_ONE, and xUART_CONFIG_PAR_ZERO select the parity mode (no parity bit, even parity bit, odd parity bit, parity bit always one, and parity bit always zero, respectively).
The ulMode parameter can be values:
xUART_IRDA_MODE_NORMAL - IrDA normal mode
Note
SIR (IrDA) operation is not supported on Sandstorm-class devices.
Returns
None.
void xUARTIrDAEnable (ulBase)
Enables SIR (IrDA) mode on the specified UART.
Parameters
ulBase is the base address of the UART port.
Enables the SIREN control bit for IrDA mode on the UART.
Returns
None.
void xUARTIrDADisable (unsigned long ulBase)
Disables SIR (IrDA) mode on the specified UART.
Parameters
ulBase is the base address of the UART port.
Clears the SIREN (IrDA) bits.
Returns
None.
void xUARTLINConfig (unsigned long ulBase, unsigned long ulBaud, unsigned long ulConfig)
Open LIN mode on the specified UART.
Parameters
ulBase is the base address of the UART port.
ulConfig is the Config of the UART port in LIN mode.
Open the LIN mode for the UART.
The ulConfig parameter is the logical OR of three values: the LIN Tx or Rx Mode, the LIN Break Field Length.
Returns
None.
void xUARTLINEnable (unsigned long ulBase)
Enables LIN Function mode on the specified UART.
Parameters
ulBase is the base address of the UART port.
Enables the SIREN control bit for LIN Function on the UART.
Returns
None.
void xUARTLINDisable (unsigned long ulBase)
Disables LIN Function mode on the specified UART.
Parameters
ulBase is the base address of the UART port.
Clears the LIN Function bits.
Returns
None.
© 2009-2011 by CooCox - visit http://www.coocox.org/