COX Shield: xADC API
xADC API
xADC
xADC API Reference
Functions
void xADCConfigure (unsigned long ulBase, unsigned long ulMode, unsigned long ulTrigger)
Configures the mode and trigger source of a sample sequence.
void xADCStepConfigure (unsigned long ulBase, unsigned long ulStep, unsigned long ulConfig)
Configure a step of the sample sequencer.
void xADCIntCallbackInit (unsigned long ulBase, xtEventCallback pfnCallback)
Init the ADC Interrupt Callback function.
void xADCIntEnable (unsigned long ulBase, unsigned long ulIntFlags)
Enable individual ADC interrupt sources.
void xADCIntDisable (unsigned long ulBase, unsigned long ulIntFlags)
Disable ADC sample sequence interrupts.
void xADCDMAEnable (unsigned long ulBase)
Enable ADC DMA operation.
void xADCDMADisable (unsigned long ulBase)
Disable ADC DMA operation.
void xADCEnable (unsigned long ulBase)
Enable ADC sample sequence.
void xADCDisable (unsigned long ulBase)
Disable the ADC sample sequence.
void xADCProcessorTrigger (unsigned long ulBase)
Cause a processor trigger for a sample sequence.
unsigned long xADCDataGet (unsigned long ulBase, unsigned long *pulBuffer)
Get the captured data for a sample sequence.
xtBoolean xADCOverflow (unsigned long ulBase)
Determine if the ADC sample sequence overflow occurred.
void xADCOverflowClear (unsigned long ulBase)
Clear the overflow condition on the ADC sample sequence.
void xADCCompConditionConfig (unsigned long ulBase, unsigned long ulCompID, unsigned long ulConfig)
Configure an ADC digital comparator.
void xADCCompRegionSet (unsigned long ulBase, unsigned long ulCompID, unsigned long ulLowRef, unsigned long ulHighRef)
Define the ADC digital comparator regions.
void xADCCompEnable (unsigned long ulBase, unsigned long ulCompID)
Enable the ADC digital comparator .
void xADCCompDisable (unsigned long ulBase, unsigned long ulCompID)
Disable the ADC digital comparator .
Detailed Description
xADC API Reference
@section xADC_Exported_APIs_Port CoX Port Details
@verbatim
//! +---------------------—+-------------—+-----—+ //! |xADC API | CoX | NUC1xx | //! |---------------------—|-------------—|-----—| //! |xADCConfigure | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCStepConfigure | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCIntCallbackInit | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCIntEnable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCIntDisable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCDMAEnable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCDMADisable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCEnable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCDisable | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCProcessorTrigger | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCDataGet | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCOverflow | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCOverflowClear | Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCCompConditionConfig | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCCompRegionSet | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCCompEnable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //! |xADCCompDisable | Non-Mandatory | Y | //! |---------------------—|-------------—|-----—| //!
Function Documentation
void xADCConfigure (unsigned long ulBase, unsigned long ulMode, unsigned long ulTrigger)
Configures the mode and trigger source of a sample sequence.
Parameters
ulBase is the base address of the ADC module.
ulMode is the sequence operation mode. Refrence xADC Operation Mode.
ulTrigger is the trigger source that initiates the sample sequence; must be one of the xADC_TRIGGER_* values. Refrence xADC Trigger Source.
Returns
None.
Referenced by KeypadButtonInit(), and SensorShieldInit().
void xADCStepConfigure (unsigned long ulBase, unsigned long ulStep, unsigned long ulConfig)
Configure a step of the sample sequencer.
Parameters
ulBase is the base address of the ADC module.
ulStep is the step to be configured.
ulConfig is the configuration of this step; must be a logical OR of xADC_CTL_TS, xADC_CTL_END, xADC_CTL_D, and one of the input channel selects (xADC_CTL_CH0 through xADC_CTL_CH7). For parts with the digital comparator feature, the follow values may also be OR'd into the ulConfig value to enable the digital comparater feature: one of the comparater selects (xADC_CTL_CMP0 through xADC_CTL_CMP1). Refrence xADC Step Config.
This function will set the configuration of the ADC for one step of a sample sequence. The ADC can be configured for single-ended or differential operation (the xADC_CTL_D bit selects differential operation when set), the channel to be sampled can be chosen (the xADC_CTL_CH0 through xADC_CTL_CH7 values), and the internal temperature sensor can be selected (the xADC_CTL_TS bit). Additionally, this step can be defined as the last in the sequence (the xADC_CTL_END bit) . If the digital comparators are present on the device, this step may also be configured send the ADC sample to the selected comparator (the xADC_CTL_CMP0 through xADC_CTL_CMP7 values). The configuration is used by the ADC at the appropriate time when the trigger for this sequence occurs.
Note
It is the responsibility of the caller to ensure that a valid configuration is specified; this function does not check the validity of the specified configuration.
Returns
None.
Referenced by KeypadButtonInit(), and SensorShieldInit().
void xADCIntCallbackInit (unsigned long ulBase, xtEventCallback pfnCallback)
Init the ADC Interrupt Callback function.
Parameters
ulBase is the base address of the ADC.
pfnCallback is the callback function.
When there is any ADC intrrupt occrus, Interrupt Handler will call the callback function.
param of pfnCallback
pvCBData not used, always 0.
ulEvent is the interrupt event..
ulMsgParam not used, always 0.
pvMsgData not used, always 0.
Returns
None.
Referenced by SensorShieldInit().
void xADCIntEnable (unsigned long ulBase, unsigned long ulIntFlags)
Enable individual ADC interrupt sources.
Parameters
ulBase is the base address of the ADC.
ulIntFlags is the bit mask of the interrupt sources to be enabled.
Enables the indicated ADC interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The ulIntFlags parameter is the logical OR of any of the following:
xADC_INT_END_CONVERSION - AD conversion interrupt
xADC_INT_COMP - Comp0 and Comp1 interrupt
Returns
None.
Referenced by SensorShieldInit().
void xADCIntDisable (unsigned long ulBase, unsigned long ulIntFlags)
Disable ADC sample sequence interrupts.
Parameters
ulBase is the base address of the ADC module.
ulIntFlags is the interrupt flags.
This function disables the requested ADC interrupts. interrupt.
Returns
None.
void xADCDMAEnable (unsigned long ulBase)
Enable ADC DMA operation.
Parameters
ulBase is the base address of the ADC module.
The specified ADC DMA features are enabled. The ADC can be configured to use DMA for transmit AD conversion data.
Returns
None.
void xADCDMADisable (unsigned long ulBase)
Disable ADC DMA operation.
Parameters
ulBase is the base address of the ADC module.
This function is used to disable ADC DMA features that were enabled by xADCDMAEnable(). The specified SSI DMA features are disabled.
Returns
None.
void xADCEnable (unsigned long ulBase)
Enable ADC sample sequence.
Parameters
ulBase is the base address of the ADC module.
Allows the specified sample sequence to be captured when its trigger is detected. A sample sequence must be configured before it is enabled.
Returns
None.
Referenced by KeypadButtonInit(), and SensorShieldInit().
void xADCDisable (unsigned long ulBase)
Disable the ADC sample sequence.
Parameters
ulBase is the base address of the ADC module.
Prevents the sample sequence from being captured when its trigger is detected. The sample sequence should be disabled before it is configured.
Returns
None.
void xADCProcessorTrigger (unsigned long ulBase)
Cause a processor trigger for a sample sequence.
Parameters
ulBase is the base address of the ADC module.
This function triggers a processor-initiated sample sequence if the sample sequence trigger is configured to xADC_TRIGGER_PROCESSOR.
Returns
None.
Referenced by KeypadButtonInit(), and SensorShieldInit().
unsigned long xADCDataGet (unsigned long ulBase, unsigned long * pulBuffer)
Get the captured data for a sample sequence.
Parameters
ulBase is the base address of the ADC module.
pulBuffer is the address where the data is stored.
This function copies data from the specified sample sequence FIFO to a memory resident buffer. The number of samples available in the FIFO are copied into the buffer, which is assumed to be large enough to hold that many samples. This will only return the samples that are presently available, which may not be the entire sample sequence if it is in the process of being executed.
Returns
Returns the number of samples copied to the buffer.
Referenced by ADCValueGet(), and KeypadButtonGet().
xtBoolean xADCOverflow (unsigned long ulBase)
Determine if the ADC sample sequence overflow occurred.
Parameters
ulBase is the base address of the ADC module.
This determines if the ADC sample sequence overflow has occurred. This will happen if the captured samples are not read from the FIFO before the next trigger occurs.
Returns
Returns xfalse if there was not an overflow, and xtrue if there was.
void xADCOverflowClear (unsigned long ulBase)
Clear the overflow condition on the ADC sample sequence.
Parameters
ulBase is the base address of the ADC module.
This will clear an overflow condition on one of the sample sequences. The overflow condition must be cleared in order to detect a subsequent overflow condition (it otherwise causes no harm).
Returns
None.
void xADCCompConditionConfig (unsigned long ulBase, unsigned long ulCompID, unsigned long ulConfig)
Configure an ADC digital comparator.
Parameters
ulBase is the base address of the ADC module.
ulCompID is the ID of the comparator to configure.
ulConfig is the configuration of the comparator.
This function will configure a comparator. The ulConfig parameter is the result of xADC_COMP_INT_xxx value. Refrence xADC Comp Interrupt Condition.
Returns
None.
Referenced by SensorShieldInit().
void xADCCompRegionSet (unsigned long ulBase, unsigned long ulCompID, unsigned long ulLowRef, unsigned long ulHighRef)
Define the ADC digital comparator regions.
Parameters
ulBase is the base address of the ADC module.
ulCompID is the ID of the comparator to configure.
ulLowRef is the reference point for the low/mid band threshold.
ulHighRef is the reference point for the mid/high band threshold.
The ADC digital comparator operation is based on three ADC value regions:
low-band is defined as any ADC value less than or equal to the ulLowRef value.
mid-band is defined as any ADC value greater than the ulLowRef value but less than or equal to the ulHighRef value.
high-band is defined as any ADC value greater than the ulHighRef value.
Returns
None.
void xADCCompEnable (unsigned long ulBase, unsigned long ulCompID)
Enable the ADC digital comparator .
Parameters
ulBase is the base address of the ADC module.
ulCompID is the comparator ID.
Enables the comparator to monitor the along input.
Returns
None.
Referenced by SensorShieldInit().
void xADCCompDisable (unsigned long ulBase, unsigned long ulCompID)
Disable the ADC digital comparator .
Parameters
ulBase is the base address of the ADC module.
ulCompID is the comparator ID.
Disables the comparator to monitor the along input.
Note
In the Stellaris Implement, The comparators do note need to enable. Users can switch to use other comparators or not use comparator function.
Returns
None.
© 2009-2011 by CooCox - visit http://www.coocox.org/