COX Shield: Sensor Shield Driver APIs
Sensor Shield Driver APIs
Sensor Shield
API Refrence of Sensor Shield Driver.
Macros
#define SensorShieldOutWrite(ulChannel, ucVal)
Write the values to the specified pin of Sensor Shield.
#define SensorShieldAInGet(ulChannel, pulVal)
Write the values to the specified pin of Sensor Shield.
#define SensorShieldInGet(ulChannel, pulVal)
Write the values to the specified pin of Sensor Shield.
Functions
void SensorShieldInit (void)
Init the sensor shield board.
void SensorShieldIOInit (void)
Init GPIO of the sensor shield board.
unsigned long SensorShieldUARTBufferGet (unsigned long ulBase, unsigned char *pucBuf, unsigned long ulLen)
get data from UART.
void SensorShieldUARTBufferPut (unsigned long ulBase, unsigned char *pucStr, unsigned long ulLen)
Send a buffer to uart.
Detailed Description
API Refrence of Sensor Shield Driver.
Macro Definition Documentation
#define SensorShieldOutWrite (ulChannel, ucVal)
Write the values to the specified pin of Sensor Shield.
Parameters
ulChannel Specified port and pin.
ucVal is the value to write to the pin(s), 0 or 1.
The parameter of ulChannel can be:
SENSOR_SHIELD_O0
SENSOR_SHIELD_O1
SENSOR_SHIELD_O2
SENSOR_SHIELD_O3
SENSOR_SHIELD_O4
SENSOR_SHIELD_O5
Write the values to the specified pin of Sensor Shield.
Returns
None
Definition at line 183 of file Sensor_Shield.h.
#define SensorShieldAInGet (ulChannel, pulVal)
Write the values to the specified pin of Sensor Shield.
Parameters
ulChannel Specified port and pin.
ucVal is the value to write to the pin(s), 0 or 1.
The parameter of ulChannel can be:
SENSOR_SHIELD_AI0
SENSOR_SHIELD_AI1
SENSOR_SHIELD_AI2
SENSOR_SHIELD_AI3
SENSOR_SHIELD_AI4
SENSOR_SHIELD_AI5
Write the values to the specified pin of Sensor Shield.
Returns
None
Definition at line 206 of file Sensor_Shield.h.
#define SensorShieldInGet (ulChannel, pulVal)
Write the values to the specified pin of Sensor Shield.
Parameters
ulChannel Specified port and pin.
ucVal is the value to write to the pin(s), 0 or 1.
The parameter of ulChannel can be:
SENSOR_SHIELD_I0
SENSOR_SHIELD_I1
SENSOR_SHIELD_I2
SENSOR_SHIELD_I3
SENSOR_SHIELD_I4
SENSOR_SHIELD_I5
Write the values to the specified pin of Sensor Shield.
Returns
None
Definition at line 239 of file Sensor_Shield.h.
Function Documentation
void SensorShieldInit (void)
Init the sensor shield board.
Parameters
None. Init the sensor shield board.
Returns
None
Definition at line 134 of file Sensor_Shield.c.
References ADCCallback(), SENSOR_SHIELD_O0, SENSOR_SHIELD_O1, SENSOR_SHIELD_O2, SENSOR_SHIELD_O3, SENSOR_SHIELD_O4, SENSOR_SHIELD_O5, SENSOR_SHIELD_TWI_SCK, SENSOR_SHIELD_TWI_SDA, xADC0_BASE, xADC_COMP_INT_LOW, xADC_CTL_CH0, xADC_CTL_CH1, xADC_CTL_CH2, xADC_CTL_CH3, xADC_CTL_CH4, xADC_CTL_CH5, xADC_INT_COMP, xADC_MODE_SCAN_CONTINUOUS, xADCCompConditionConfig(), xADCCompEnable(), xADCConfigure(), xADCEnable(), xADCIntCallbackInit(), xADCIntEnable(), xADCProcessorTrigger(), xADCStepConfigure(), xGPIOSPinToPeripheralId, xGPIOSPinTypeGPIOInput, xGPIOSPinTypeGPIOOutput, xI2CMasterInit(), xINT_ADC0, xIntEnable(), xSYSCTL_PERIPH_ADC0, xSYSCTL_UART1_MAIN, xSysCtlPeripheralClockSourceSet(), xSysCtlPeripheralEnable(), xSysCtlPeripheralEnable2(), xUART_CONFIG_PAR_NONE, xUART_CONFIG_STOP_1, xUART_CONFIG_WLEN_8, and xUARTConfigSet().
void SensorShieldIOInit (void)
Init GPIO of the sensor shield board.
Parameters
None. Init GPIO of the sensor shield board.
Returns
None
Definition at line 291 of file Sensor_Shield.c.
References SENSOR_SHIELD_O0, SENSOR_SHIELD_O1, SENSOR_SHIELD_O2, SENSOR_SHIELD_O3, SENSOR_SHIELD_O4, SENSOR_SHIELD_O5, xGPIOSPinTypeGPIOInput, xGPIOSPinTypeGPIOOutput, and xGPIOSPinWrite.
unsigned long SensorShieldUARTBufferGet (unsigned long ulBase, unsigned char * pucBuf, unsigned long ulLen)
get data from UART.
Parameters
pucBuf is the point of data will be save.
ulLen is the lenth of data will be save.
get data from UART.
Returns
the lenth of data
Definition at line 95 of file Sensor_Shield.c.
References xUARTCharGet().
void SensorShieldUARTBufferPut (unsigned long ulBase, unsigned char * pucStr, unsigned long ulLen)
Send a buffer to uart.
Parameters
ulBase is the base address of the UART port.
pucStr is the point of data will be sent.
ulLen is the lenth of data will be sent.
Send a buffer to uart
Returns
None
Definition at line 73 of file Sensor_Shield.c.
References xUARTCharPut().
© 2009-2011 by CooCox - visit http://www.coocox.org/