COX Shield: xTIMER API
xTIMER API
xTIMER
xTIMER API Reference.
Functions
void xTimerInitConfig (unsigned long ulBase, unsigned long ulChannel, unsigned long ulConfig, unsigned long ulTickFreq)
Configurate The Timer's mode and tick frequency.
void xTimerStart (unsigned long ulBase, unsigned long ulChannel)
Start The Timer counter.
void xTimerStop (unsigned long ulBase, unsigned long ulChannel)
Stop The Timer counter.
void xTimerCounterEnable (unsigned long ulBase, unsigned long ulChannel)
Enable The Timer counter as a counter.
void xTimerCounterDisable (unsigned long ulBase, unsigned long ulChannel)
Disable The Timer counter as a counter.
void xTimerCaptureModeSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulCapMode)
Enable The Timer counter as a capture.
void xTimerPrescaleSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulValue)
Set The Timer counter Prescale Value.
unsigned long xTimerPrescaleGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter Prescale Value.
void xTimerLoadSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulValue)
Set The Timer counter Value.
unsigned long xTimerLoadGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter Value.
unsigned long xTimerValueGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter current up timer or up event counter value.
void xTimerMatchSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulValue)
Set The Timer counter Compare Match Value.
unsigned long xTimerMatchGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter Compare Match Value.
void xTimerIntCallbackInit (unsigned long ulBase, xtEventCallback xtTimerCallback)
Init interrupts callback for the timer.
void xTimerIntEnable (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags) extern void xTimerIntDisable(unsigned long ulBase
Enable The Timer counter interrupt.
void xTimerStatusGet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags)
Get The Timer counter interrupt Status.
void xTimerCounterDetectPhaseSelect (unsigned long ulBase, unsigned long ulChannel, unsigned long ulPhase)
Select The Timer counter detect phase.
void xTimerCaptureEdgeSelect (unsigned long ulBase, unsigned long ulChannel, unsigned long ulEdge)
Select The Timer counter capture detect edge.
Variables
void unsigned long ulChannel
void unsigned long unsigned long ulIntFlags
Detailed Description
xTIMER API Reference.
@section xTIMER_Exported_APIs_Port CoX Port Details
@verbatim
//! +---------------------------—+-------------—+---------------—+ //! |xTIMER API | CoX | NUC1xx | //! |---------------------------—|-------------—|---------------—| //! |xTimerInitConfig | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerStart | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerStop | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerCounterEnable | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerCounterDisable | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerCaptureModeSet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerPrescaleSet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerPrescaleGet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerLoadSet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerLoadGet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerValueGet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerMatchSet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerMatchGet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerIntCallbackInit | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerIntEnable | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerIntDisable | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerStatusGet | Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerCounterDetectPhaseSelect| Mandatory | Y | //! |---------------------------—|-------------—|---------------—| //! |xTimerCaptureEdgeSelect | Mandatory | Y | //! +---------------------—+-------------—+---------------------—+ //!
Function Documentation
void xTimerInitConfig (unsigned long ulBase, unsigned long ulChannel, unsigned long ulConfig, unsigned long ulTickFreq)
Configurate The Timer's mode and tick frequency.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulConfig is the mode Configuratation of the Timer port. Details please refer to xTIMER Count Direction and xTIMER Mode Type
ulTickFreq is the tick frequency of the Timer port.
This function is to configurate The Timer's mode and tick frequency.
The ulConfig parameter is the OR value of two values:
Timer's mode Details please refer to 2. CoX Port Details
Timer's direction Details please refer to 2. CoX Port Details
xTIMER_MODE_ONESHOT, xTIMER_MODE_PERIODIC, xTIMER_MODE_TOGGLE and xTIMER_MODE_CONTINUOUS is the Timer's mode
xTIMER_COUNT_UP, xTIMER_COUNT_DOWN is the Timer's direction.
The ulTickFreq parameter is the the timer tick frequency.It can be any values but ulTickFreq > 0 and ulTickFreq < timer clock source.
Note
For nuc1xx,each timer only one channel.
Returns
None.
Referenced by MSDelay().
void xTimerStart (unsigned long ulBase, unsigned long ulChannel)
Start The Timer counter.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to start The Timer counter.
Returns
None.
Referenced by MSDelay().
void xTimerStop (unsigned long ulBase, unsigned long ulChannel)
Stop The Timer counter.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to stop The Timer counter.
Returns
None.
Referenced by MSDelay().
void xTimerCounterEnable (unsigned long ulBase, unsigned long ulChannel)
Enable The Timer counter as a counter.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to enable The Timer counter as a counter.
Returns
None.
void xTimerCounterDisable (unsigned long ulBase, unsigned long ulChannel)
Disable The Timer counter as a counter.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to disable The Timer counter as a counter.
Returns
None.
void xTimerCaptureModeSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulCapMode)
Enable The Timer counter as a capture.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulCapMode is the capture mode of the Timer port.Which can be the values: TIMER_CAP_MODE_CAP, TIMER_CAP_MODE_RST. Details please refer to xTIMER Capture Mode Type
This function is to enable The Timer counter as a capture.
Returns
None.
void xTimerPrescaleSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulValue)
Set The Timer counter Prescale Value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulValue is the Prescale Value will be set.
This function is to Set The Timer counter Prescale Value.
Returns
None.
unsigned long xTimerPrescaleGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter Prescale Value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to get The Timer counter Prescale Value.
Returns
the Prescale Value will be get.
void xTimerLoadSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulValue)
Set The Timer counter Value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulValue is the Prescale Value will be set.
This function is to Set The Timer counter Value.
Returns
None.
unsigned long xTimerLoadGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter Value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to get The Timer counter Prescale Value.
Returns
the counter Value will be get.
unsigned long xTimerValueGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter current up timer or up event counter value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to get The Timer counter current up timer or up event counter value.
Returns
current up timer or up event counter value will be set.
void xTimerMatchSet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulValue)
Set The Timer counter Compare Match Value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulValue is Timer counter Compare Match Value.
This function is to Set The Timer counter Compare Match Value.
Returns
None.
unsigned long xTimerMatchGet (unsigned long ulBase, unsigned long ulChannel)
Get The Timer counter Compare Match Value.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
This function is to get The Timer counter Compare Match Value.
Returns
the Prescale Value will be set.
void xTimerIntCallbackInit (unsigned long ulBase, xtEventCallback xtTimerCallback)
Init interrupts callback for the timer.
Parameters
ulBase is the base address of the Timer port.
xtPortCallback is callback for the timer.
Init interrupts callback for the timer.
Returns
None.
void xTimerIntEnable (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags)
Enable The Timer counter interrupt.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulIntFlags is the interrupt type of the Timer port. Details please refer to xTIMER Interrupt
This function is to enable The Timer counter interrupt.
The ulIntFlags parameter is the OR value of any of the following: xTIMER_INT_MATCH, xTIMER_INT_CAP_EVENT. Details please refer to
CoX Port Details
Returns
None. Disable The Timer counter interrupt.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulIntFlags is the interrupt type of the Timer port. Details please refer to xTIMER Interrupt.
This function is to disable The Timer counter interrupt.
The ulIntFlags parameter is the OR value of any of the following: xTIMER_INT_MATCH, xTIMER_INT_CAP_EVENT. Details please refer to
CoX Port Details
.
Note
None
Returns
None.
Referenced by MSDelay().
void xTimerStatusGet (unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags)
Get The Timer counter interrupt Status.
Parameters
ulBase is the base address of the Timer port.
ulChannel is the channel of the Timer port. Details please refer to xTIMER Count Channel
ulIntFlags is the interrupt type of the Timer port. Details please refer to xTIMER Interrupt.
This function is to disable The Timer counter interrupt.
The ulIntFlags parameter can be one of the values: xTIMER_INT_MATCH, xTIMER_INT_CAP_EVENT. Details please refer to
CoX Port Details
.
Note
When use this API ,the ulIntFlags parameter one of the interrupt event
Returns
the Status of The Timer counter interrupt.
Referenced by MSDelay().
void xTimerCounterDetectPhaseSelect (unsigned long ulBase, unsigned long ulChannel, unsigned long ulPhase)
Select The Timer counter detect phase.
Parameters
ulBase is the base address of the Timer port.
ulPhase is the counter detect phase of the Timer port. Details please refer to xTIMER Counter Pase Type.
This function is to select The Timer counter detect phase.
The ulPhase parameter can be one of the values: xTIMER_COUNTER_RISING, xTIMER_COUNTER_FALLING. Details please refer to
CoX Port Details
.
Note
None
Returns
None.
void xTimerCaptureEdgeSelect (unsigned long ulBase, unsigned long ulChannel, unsigned long ulEdge)
Select The Timer counter capture detect edge.
Parameters
ulBase is the base address of the Timer port.
ulEdge is the capture detect edge of the Timer port. Details please refer to xTIMER Capture Edge Type.
This function is to select The Timer counter capture detect edge.
The ulPhase parameter can be one of the values: xTIMER_CAP_RISING, xTIMER_CAP_FALLING, xTIMER_CAP_BOTH. Details please refer to
CoX Port Details
.
Note
None
Returns
None.
Variable Documentation
void unsigned long ulChannel
Definition at line 769 of file xtimer.h.
void unsigned long unsigned long ulIntFlags
Definition at line 769 of file xtimer.h.
© 2009-2011 by CooCox - visit http://www.coocox.org/