COX Shield: Keypad Driver APIs
Keypad Driver APIs
LCD Shield
API Refrence of Keypad Driver.
Functions
void KeypadButtonInit (void)
Init the HD44780 LCD Keypad.
int KeypadButtonGet (void)
Get the button value of LCD Keypad.
Detailed Description
API Refrence of Keypad Driver.
Function Documentation
void KeypadButtonInit (void)
Init the HD44780 LCD Keypad.
Parameters
None
Returns
None.
Definition at line 60 of file LCDKeypad.c.
References ADC0, xADC0_BASE, xADC_CTL_CH0, xADC_MODE_SCAN_CONTINUOUS, xADCConfigure(), xADCEnable(), xADCProcessorTrigger(), xADCStepConfigure(), xSPinTypeADC, xSYSCTL_PERIPH_ADC0, and xSysCtlPeripheralEnable().
int KeypadButtonGet (void)
Get the button value of LCD Keypad.
Parameters
None
Returns
The button value of LCD Keypad.
Definition at line 101 of file LCDKeypad.c.
References xADC0_BASE, and xADCDataGet().
© 2009-2011 by CooCox - visit http://www.coocox.org/