COX Shield: E:/rongdong/git/shining.git/CoX/Shield/Adafruit_Industries/LCD_Shield/lib/hd44780.c File Reference
hd44780.c File Reference
Driver for Character LCD HD44780.
#include "xhw_types.h"
#include "xhw_memmap.h"
#include "xhw_ints.h"
#include "xdebug.h"
#include "xsysctl.h"
#include "xgpio.h"
#include "hw_hd44780.h"
#include "hd44780.h"
#include "coshining.h"
Functions
void HD44780Write (unsigned char ucRS, unsigned char ucInstruction)
Write data or command to the HD44780.
unsigned char HD44780Read (unsigned char ucRS)
Read the state or data from the HD44780.
void HD44780WriteCmd (unsigned char ucCmd)
void HD44780WriteData (unsigned char ucData)
unsigned long HD44780ReadState (void)
Read the state of the HD44780.
xtBoolean HD44780Busy (void)
determine if the HD44780 is busy.
unsigned long HD44780ReadData (void)
Read data from the HD44780 DDRAM.
void HD44780Init (void)
Init the HD44780 LCD Device.
void HD44780EntryModeSet (unsigned char ucCursorMoveDirection, xtBoolean bDisplayShift)
Set the the LCD entry mode.
void HD44780DisplayClear (void)
Clears the LCD display.
void HD44780DisplayOn (void)
Sets the entire LCD display on.
void HD44780DisplayOff (void)
Sets the entire LCD display off.
void HD44780CursorOn (xtBoolean bBlink)
Sets cursor on.
void HD44780CursorOff (void)
Sets cursor off.
void HD44780DisplayString (const char *pcString)
Display a string on the LCD.
void HD44780DisplayN (unsigned long n)
Display a decimal number on the LCD.
void HD44780Home (void)
Cursor back to Home.
void HD44780LocationSet (unsigned char x, unsigned char y)
Set the cursor location.
void HD44780CursorLeftMove (unsigned char n)
Move the cursor n unit to the left.
void HD44780CursorRightMove (unsigned char n)
Move the cursor n unit to the right.
void HD44780DisplayLeftShift (unsigned char n)
Shift the entire display n unit to the left.
void HD44780DisplayRightShift (unsigned char n)
Shift the entire display n unit to the right.
Detailed Description
Driver for Character LCD HD44780.
Version
2.1.1.0
Date
10/18/2011
Author
CooCox
Copyright (c) 2011, CooCox All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the <ORGANIZATION> nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file hd44780.c.
Function Documentation
void HD44780Write (unsigned char ucRS, unsigned char ucInstruction)
Write data or command to the HD44780.
Parameters
ucRS determines if the IR or DR to select.
The parameter of ucRS can be:
HD44780_RS_COMMAND - select the IR.
HD44780_RS_DATA - select the DR.
Returns
None.
Definition at line 64 of file hd44780.c.
References HD44780_E_DISABLE, HD44780_E_ENABLE, HD44780_PIN_D4, HD44780_PIN_D5, HD44780_PIN_D6, HD44780_PIN_D7, HD44780_PIN_E, HD44780_PIN_RS, HD44780_PIN_RW, HD44780_RS_COMMAND, HD44780_RS_DATA, HD44780_RW_WRITE, xASSERT, xGPIOSPinWrite, and xSysCtlDelay().
Referenced by HD44780WriteCmd(), and HD44780WriteData().
unsigned char HD44780Read (unsigned char ucRS)
Read the state or data from the HD44780.
Parameters
ucRS determines if the IR or DR to select.
The parameter of ucRS can be:
HD44780_RS_COMMAND - select the IR.
HD44780_RS_DATA - select the DR.
Returns
None.
Definition at line 117 of file hd44780.c.
References HD44780_E_DISABLE, HD44780_E_ENABLE, HD44780_PIN_D4, HD44780_PIN_D5, HD44780_PIN_D6, HD44780_PIN_D7, HD44780_PIN_E, HD44780_PIN_RS, HD44780_PIN_RW, HD44780_RS_COMMAND, HD44780_RS_DATA, HD44780_RW_READ, xASSERT, xGPIOSPinRead, xGPIOSPinTypeGPIOInput, xGPIOSPinTypeGPIOOutput, xGPIOSPinWrite, and xSysCtlDelay().
Referenced by HD44780ReadData(), and HD44780ReadState().
© 2009-2011 by CooCox - visit http://www.coocox.org/